name: Build for Windows

on:
  release:
    types: [created]

env:
  BUILD_TYPE: Release
  BUILD_FILENAME: hangman
  APP_EXECUTABLE_FILENAME: Hangman
  QT_ARCH: win64_msvc2019_64
  QT_VERSION: "6.4.2"

jobs:
  build-windows-64:
    name: Windows Latest
    runs-on: windows-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          host: windows
          target: "desktop"
          version: ${{ env.QT_VERSION }}
          arch: ${{ env.QT_ARCH }}
          dir: "${{ github.workspace }}/qt"
          install-deps: "true"
          setup-python: "false"

      - name: Configure
        working-directory: ${{ github.workspace }}
        run: cmake -B./build -S. ${{ github.workspace }} \
          -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
          -DCMAKE_PREFIX_PATH=${{ env.Qt6_Dir }}

      - name: Build
        working-directory: ${{ github.workspace }}
        run: cmake --build ./build --config ${{ env.BUILD_TYPE }} -j 24

      - name: Deploy
        working-directory: ${{ github.workspace }}
        run: windeployqt.exe ./bin/${{ env.BUILD_TYPE }}/${{ env.APP_EXECUTABLE_FILENAME }}.exe \
          --verbose 1 \
          --release \
          --no-svg \
          --no-opengl \
          --no-opengl-sw \
          --no-translations \
          --no-compiler-runtime \
          --no-system-d3d-compiler \

      - name: Move bin
        run: |
          Move-Item -Path '${{ github.workspace }}\bin\${{ env.BUILD_TYPE }}\*' -Destination '${{ github.workspace }}\bin\'

      - name: Delete old folders
        run: |
          Remove-Item -Path '${{ github.workspace }}\bin\${{ env.BUILD_TYPE }}' -Recurse

      - name: Compress bin
        run: |
          Compress-Archive -Path '${{ github.workspace }}\bin','${{ github.workspace }}\resources' -DestinationPath ${{ github.workspace }}\${{ env.BUILD_FILENAME }}.${{ github.ref_name }}.zip

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/${{ env.BUILD_FILENAME }}.${{ github.ref_name }}.zip
          tag: ${{ github.ref }}
          overwrite: false
